### ISSUE TITLE
Write-up of project proposal in Wiki

### ISSUE THREAD

**Issue by hlac** [taranjitsinghboparai/COMP313-002-Team4#1]

**Comment by sapreetbhutta** [comment]
We need to discuss the complete goals and time frame for this proposal

**Comment by hlac** [comment]
@sapreetbhutta The end of Iteration 1 is Feb 5.  Check the Milestones.

**Comment by Navjot304** [comment]
Comparing other available web portals selling video games, we set a proposed solution to solve problems we found on those available web portals.
