### ISSUE TITLE
Categories for Games

### ISSUE THREAD

**Issue by taranjitsinghboparai** [taranjitsinghboparai/COMP313-002-Team4#11]
Please give your ideas about the categories we have to include in our website and android application. Eg: Sports, Action.

**Comment by taranjitsinghboparai** [comment]
1. Sports
2. Action
3. Role playing

**Comment by shivampatel3033** [comment]
Sports
Fps
Openworld
Strategy
Adventure
RPG
Arcade
Puzzle etc
