### ISSUE TITLE
Platforms for Games

### ISSUE THREAD

**Issue by taranjitsinghboparai** [taranjitsinghboparai/COMP313-002-Team4#12]
Example : PC games, Playstation and so on

**Comment by taranjitsinghboparai** [comment]
1. Pc
2. Playstation 4
3. Playstation 3
4. Xbox
5. PSP
6. Nintendo

**Comment by taranjitsinghboparai** [comment]
Do you guys want to add Playstation 2 games as well? I think Playstation 2 is outdated. Please post your comments on this.

**Comment by shivampatel3033** [comment]
We can remove psp nintendo and ps2

**Comment by taranjitsinghboparai** [comment]
Psp and nitendo roms are still used by lot of people out there. Many people play nitendo games on emulators. Let see what all the members of the group decide.

**Comment by jp1433** [comment]
We can do both psp and nintendo. It won't matter if it is old or not we will try to put maximum 4-5 platforms

**Comment by jaspreetboparai** [comment]
How many games for one section ??

**Comment by jp1433** [comment]
We can put the same games for each platform. Only the price and download links will be different. For example, we can put a game and add different links to it which will go to download page for different platforms

**Comment by jaspreetboparai** [comment]
Yeah providing different links for xbox, ps3 and so on

**Comment by ghost** [comment]
Yeah like:
Available on PS3, XBox or whatever platforms the game is available.

**Comment by taranjitsinghboparai** [comment]
Yeah we can create same page for the game and add links for different platforms to buy the game

**Comment by jaspreetboparai** [comment]
Then we have to put reviews on respective buy the game pages. Right ??

**Comment by taranjitsinghboparai** [comment]
Please post in issue for features
