### ISSUE TITLE
Search games from homepage feature for website

### ISSUE THREAD

**Issue by taranjitsinghboparai** [taranjitsinghboparai/COMP313-002-Team4#13]
I am thinking about having a search feature in website that will allow the user to search the available games from homepage. Any comments?

**Comment by shivampatel3033** [comment]
We can do that. Or we can also add advance search feature like finding it by keywords or by year.

**Comment by taranjitsinghboparai** [comment]
Yeah finding by keywords seems great.

**Comment by jaspreetboparai** [comment]
Yeah such as one keyword typed can display all the games having that keyword

**Comment by jp1433** [comment]
Sounds good

**Comment by jaspreetboparai** [comment]
Yeah then we could go with it

**Comment by ghost** [comment]
I think we can add another feature to rate games.

**Comment by ghost** [comment]
And for the search feature we can have categories for the games.

**Comment by ghost** [comment]
like:
Action 
Adventure
Puzzle 
Sports
First Person Shooter

**Comment by jaspreetboparai** [comment]
Yeahh and also providing feedback at the end of description

**Comment by ghost** [comment]
and more

**Comment by jaspreetboparai** [comment]
Yeahhh sounds great
