### ISSUE TITLE
Features for Project

### ISSUE THREAD

**Issue by taranjitsinghboparai** [taranjitsinghboparai/COMP313-002-Team4#14]
Everyone please post your ideas about features here.

**Comment by taranjitsinghboparai** [comment]
1. Searching the games with Keywords.
2. Links for different platforms on same page of game.

**Comment by ghost** [comment]
Maybe Latest Arrivals?

**Comment by taranjitsinghboparai** [comment]
Yeah Upcoming Games

**Comment by ghost** [comment]
We can add Popular Game feature based on the games ordered the most

**Comment by jp1433** [comment]
We can make a page which will have the games which are on discount like discount page/ deals

**Comment by jp1433** [comment]
Each game page will contain description,several links for different platforms and a ratings feature so that We do not need to add ratings feature to all the links i.e. 1 ratings feature per game.

**Comment by Avjot** [comment]
We can create a wishlist for customers also

**Comment by Avjot** [comment]
Add to cart is an important feature of any website. So we have to implement that

**Comment by Avjot** [comment]
Rating of games is a good feature to implement

**Comment by sapreetbhutta** [comment]
Keywords search 
And wishlist is better idea for returning customers
