### ISSUE TITLE
As a User, I can search the available Games

### ISSUE THREAD

**Issue by Avjot** [taranjitsinghboparai/COMP313-002-Team4#15]

**Comment by Avjot** [comment]
Search can be done on basis of:
1. Categories
2. Platforms
3. Keywords
What you think guys?How we should do it?

**Comment by shivampatel3033** [comment]
I think categories is the best as the user will be searching games according to the genre of the game. For eg some like racing games and some like shooting games. And if he clicks any game the platform choice would be on same page. So there is no point of doing it by platform.

**Comment by jp1433** [comment]
Yes that's right we should only add search by categories and maybe keywords too.

**Comment by taranjitsinghboparai** [comment]
For categorizing the games we can arrange them in different categories and we can add a page of categories to website.

**Comment by shivampatel3033** [comment]
Yes, that's a good idea.

**Comment by taranjitsinghboparai** [comment]
For searching the games, we can use keywords for searching. Eg: If the user searches "NFS" in search bar the website should give results of all the games having "NFS" in the name.

**Comment by sapreetbhutta** [comment]
I think categories is better because normally we search with it and keyword is also a better option

**Comment by Avjot** [comment]
Ok. We will add search according to keywords and we will differentiate the games according to categories

**Comment by taranjitsinghboparai** [comment]
![8](https://cloud.githubusercontent.com/assets/22568394/23585476/2d700764-014e-11e7-83a4-1255aede94ec.JPG)

**Comment by taranjitsinghboparai** [comment]
closed
