### ISSUE TITLE
As a User, I can add games to my shopping cart so that I can checkout with credit cards and PayPal.

### ISSUE THREAD

**Issue by Avjot** [taranjitsinghboparai/COMP313-002-Team4#16]

**Comment by taranjitsinghboparai** [comment]
Yeah we can allow the user to add the games to cart for purchasing multiple games at once.

**Comment by Navjot304** [comment]
When the customer refreshes the browser, will the cart show added items or not? Or the customer has to begin it again?

**Comment by taranjitsinghboparai** [comment]
We can use session management for that. It will show the items until the session is not expired.

**Comment by Avjot** [comment]
Yes, we have to store all purchases of customer during his session
