### ISSUE TITLE
As a User, I can rate any games

### ISSUE THREAD

**Issue by Avjot** [taranjitsinghboparai/COMP313-002-Team4#17]

**Comment by Avjot** [comment]
We can do rating with the help of stars or numbers. Any other idea

**Comment by jp1433** [comment]
Ratings with stars will be a good idea

**Comment by taranjitsinghboparai** [comment]
I think rating based on stars is good and it will look good on website too.

**Comment by sapreetbhutta** [comment]
Yeah stars look better

**Comment by Navjot304** [comment]
Yes rating with stars will look better as we are creating an entertainment related website and app

**Comment by Avjot** [comment]
Ok. We will do with stars then
