### ISSUE TITLE
As a user I can rate the games

### ISSUE THREAD

**Issue by jp1433** [taranjitsinghboparai/COMP313-002-Team4#18]

**Comment by taranjitsinghboparai** [comment]
taranjitsinghboparai/COMP313-002-Team4#17

**Comment by hlac** [comment]
Is this issue done?  If yes, please close the issue via commit messages
using the keywords from the following
https://help.github.com/articles/closing-issues-via-commit-messages/.


Best Regards,
Hao C. Lac, Ph.D. (Computational Science)

**Comment by taranjitsinghboparai** [comment]
No Sir, someone started a duplicate issue. So I referenced this issue to the other one and closed it.
