### ISSUE TITLE
System setup and configuration

### ISSUE THREAD

**Issue by hlac** [taranjitsinghboparai/COMP313-002-Team4#2]
- Decide on a cloud service to host your backend data
- Preferred database is nosql

**Comment by taranjitsinghboparai** [comment]
Any suggestions for hosting service?

**Comment by HATELA** [comment]
we can do Azure or google cloud platform.

**Comment by taranjitsinghboparai** [comment]
yeah I think Azure is good as we get 30-days Trail and we can use any type of Database.

**Comment by Navjot304** [comment]
What about after 30-days trial period?

**Comment by jp1433** [comment]
we only need azure to publish the website which will be at the end of the semester. we will open a azure account around that time so that we can publish the website and show it to professor.

**Comment by taranjitsinghboparai** [comment]
Yeah until that we need to develop and run our website on local host. In the month of semester, we'll create azure account and pubilsh the website over there.

**Comment by taranjitsinghboparai** [comment]
Last Month*

**Comment by sapreetbhutta** [comment]
Yeah azure account will be fine for hosting.

**Comment by jaspreetboparai** [comment]
sounds good

**Comment by jaspreetboparai** [comment]
but we have to do buy the subscription after one month

**Comment by jp1433** [comment]
it wont be necessary as we will start the free subscription during the last month of the semester. we will publish the website on azure and show it to the professor. After that we can delete the account.

**Comment by sapreetbhutta** [comment]
Okk

**Comment by jaspreetboparai** [comment]
Well then azure is good

**Comment by Navjot304** [comment]
If we are creating local database for now and then for azure, we have to create it again. Is that fine? We have double-work.

**Comment by Avjot** [comment]
We can try to find other free cloud services so that we do not have to wait for last month to make database on azure

**Comment by hlac** [comment]
Final decision:
1) Xamarin.
2) Azure.
3) Selenium
