### ISSUE TITLE
As a User, I can add games to Wishlist to buy them later

### ISSUE THREAD

**Issue by taranjitsinghboparai** [taranjitsinghboparai/COMP313-002-Team4#21]

**Comment by hlac** [comment]
Perhaps you mean "As a User, I can save games to a Wishlist so that I can
purchase them later, inventory permitting"?


Best Regards,
Hao C. Lac, Ph.D. (Computational Science)

**Comment by taranjitsinghboparai** [comment]
No Sir, If user want to save a game to buy later. Then user can add that game to wishlist.

**Comment by taranjitsinghboparai** [comment]
closed
