### ISSUE TITLE
As a User, I can register to the website

### ISSUE THREAD

**Issue by taranjitsinghboparai** [taranjitsinghboparai/COMP313-002-Team4#22]

**Comment by hlac** [comment]
These are two separate stories.


Best Regards,
Hao C. Lac, Ph.D. (Computational Science)

**Comment by taranjitsinghboparai** [comment]
Ok Sir

**Comment by jaspreetboparai** [comment]
![2](https://cloud.githubusercontent.com/assets/22568573/23577275/ce5bc0d0-0088-11e7-9859-7a3d244bbaed.JPG)
