### ISSUE TITLE
As a User, I can filter Games based on Genre/Categories

### ISSUE THREAD

**Issue by taranjitsinghboparai** [taranjitsinghboparai/COMP313-002-Team4#25]

**Comment by Avjot** [comment]
![4](https://cloud.githubusercontent.com/assets/22561885/23575190/d211720e-004e-11e7-884f-936fe1d13f82.JPG)


I have completed this user story. Look at the screenshot. Anyone want to suggest some change?

**Comment by Avjot** [comment]
![9](https://cloud.githubusercontent.com/assets/22561885/23579023/b107f5fa-00a9-11e7-8259-b75f4c90cfe8.JPG)
