### ISSUE TITLE
Use Case Diagram for both Registered and Unregistered User 

### ISSUE THREAD

**Issue by taranjitsinghboparai** [taranjitsinghboparai/COMP313-002-Team4#29]
![use case](https://cloud.githubusercontent.com/assets/22568394/23110405/2bc04e2e-f6ef-11e6-965c-7b280d3b4eca.JPG)

I have created this Use Case Diagram for User. Please review it and tell me if you have any more ideas to add to this use case.

**Comment by jaspreetboparai** [comment]
Its good. We can add more ideas later on.

**Comment by jp1433** [comment]
There should be an option to purchase and checkout for the registered users.

**Comment by taranjitsinghboparai** [comment]
sure @jp1433

**Comment by Avjot** [comment]
User on one side should be our system which is communicating with the user. Registered and unregistered user should be on one side

**Comment by Navjot304** [comment]
Even i think system should be included in diagram

**Comment by hlac** [comment]
Navjot is correct.  A user role can be a non-human user.  Instead of
calling your system "System", a friendlier name might make writing stories
less of a chore (e.g., Apple calls their voice system "Siri").


Best Regards,
Hao C. Lac, Ph.D. (Computational Science)

**Comment by Avjot** [comment]
GameVault can be one name for our system

**Comment by hlac** [comment]
I would avoid names that convey inanimateness since it would be no
different from "System".


Best Regards,
Hao C. Lac, Ph.D. (Computational Science)

**Comment by Avjot** [comment]
Is "Gamers" ok?

**Comment by taranjitsinghboparai** [comment]
We'll use keyword "System" for the use cases.
