### ISSUE TITLE
Mobile front-end and testing

### ISSUE THREAD

**Issue by hlac** [taranjitsinghboparai/COMP313-002-Team4#3]
TBD

**Comment by hlac** [comment]
Proceed with decision asap.

**Comment by hlac** [comment]
Since you are implementing a project using asp.net, testing is expected since you are very familiar with this technology and you've implemented something similar in another course (i.e., selling balloons).

**Comment by taranjitsinghboparai** [comment]
We can develop Android Application for our website. Suggestions?

**Comment by jp1433** [comment]
I think we can use Xamarin studio for converting ASP.NET website to Android Application.

**Comment by taranjitsinghboparai** [comment]
Ok so for now we'll focus on developing website. After developing website we'll discuss about using Xamarin Studio or Android Studio.

**Comment by taranjitsinghboparai** [comment]
So what about testing?

**Comment by jaspreetboparai** [comment]
yeah testing is the main problem. Someone came up with any ideas ?

**Comment by jp1433** [comment]
we can use testing tools like NUnitAsp, TestCafe, Selenium

**Comment by Avjot** [comment]
Also we have to divide the work between us who is doing what

**Comment by miherlosev** [comment]
Hi,
I am developer from [TestCafe](https://github.com/DevExpress/testcafe) team.
I can help you setup CI, write a first tests set and much more.

**Comment by taranjitsinghboparai** [comment]
Hi Miherlosev,
Thankyou for that but this is our school project. First we need to confirm from Professor that is it allowed or not.

**Comment by hlac** [comment]
I didn't realize that your team is working on an industry-based project?


Regards,
Hao C. Lac, Ph.D. (Computational Science)
